#cloud-config
write_files:
  - path: /etc/weave.env
    permissions: 0644
    owner: root
    content: |
      WEAVE_CLUSTER_SIZE={{WEAVE_CLUSTER_SIZE}}

coreos:
  etcd2:
    name: {{ETCD_NODE_NAME}}
    discovery: https://discovery.etcd.io/{{ETCD_DISCOVERY_TOKEN}}
    advertise-client-urls: http://$private_ipv4:2379
    initial-advertise-peer-urls: http://$private_ipv4:2380
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    listen-peer-urls: http://$private_ipv4:2380,http://$private_ipv4:7001
  fleet:
    public-ip: "$public_ipv4"
    metadata: {{FLEET_METADATA}}
  flannel:
    interface: "$public_ipv4"
  units:
  - name: fleet.socket
    command: start
    drop-ins:
    - name: 30-ListenStream.conf
      content: |
        [Socket]
        ListenStream=49153

  - name: etcd2.service
    command: start

  - name: fleet.service
    command: start

  - name: flanneld.service
    drop-ins:
    - name: 50-network-config.conf
      content: |
        [Service]
        ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{ "Network": "172.17.0.0/16" }'
    command: start

  - name: docker-tcp.socket
    command: start
    enable: true
    content: |-
      [Unit]
      Description=Docker Socket for the API

      [Socket]
      ListenStream=2375
      Service=docker.service
      BindIPv6Only=both

      [Install]
      WantedBy=sockets.target

  - name: 10-weave.network
    runtime: false
    content: |
      [Match]
      Type=bridge
      Name=weave*

      [Network]
  - name: install-weave.service
    command: start
    enable: true
    content: |
      [Unit]
      After=network-online.target
      After=docker.service
      Description=Install Weave
      Documentation=http://zettio.github.io/weave/
      Requires=network-online.target
      Requires=docker.service

      [Service]
      Type=oneshot
      RemainAfterExit=yes
      ExecStartPre=/usr/bin/wget -N -P /opt/bin https://raw.githubusercontent.com/weaveworks/weave/master/weave
      ExecStartPre=/usr/bin/chmod +x /opt/bin/weave
      ExecStartPre=/usr/bin/docker pull weaveworks/weave
      ExecStartPre=/usr/bin/docker pull weaveworks/weavedb
      ExecStartPre=/usr/bin/docker pull weaveworks/plugin
      ExecStartPre=/usr/bin/docker pull weaveworks/weaveexec
      ExecStart=/bin/echo Wave Installed
  
  - name: install-weave-startup.service
    command: start
    enable: true
    content: |
      [Unit]
      After=install-weave.service
      After=docker.service
      Description=Install Weave Startup Script
      Requires=install-weave.service
      Requires=docker.service

      [Service]
      Type=oneshot
      RemainAfterExit=yes
      ExecStartPre=/usr/bin/wget -N -P /opt/bin https://raw.githubusercontent.com/aweris/core-os/master/weave_startup
      ExecStartPre=/usr/bin/chmod +x /opt/bin/weave_startup
      ExecStart=/bin/echo Wave Startup Installed

  - name: weave.service
    command: start
    enable: true
    content: |
      [Unit]
      After=install-weave-startup.service
      Description=Weave Network
      Documentation=http://zettio.github.io/weave/
      Requires=install-weave-startup.service

      [Service]
      EnvironmentFile=/etc/weave.env
      ExecStartPre=/opt/bin/weave_startup $WEAVE_CLUSTER_SIZE
      ExecStart=/usr/bin/docker attach weave
      ExecStop=/opt/bin/weave stop
      
      [Install]
      WantedBy=multi-user.target
      
  - name: install-weave-network.service
    command: start
    enable: true
    content: |
      [Unit]
      After=weave.service
      Description=Create IBE Development Weave Network
      Documentation=http://zettio.github.io/weave/
      Requires=weave.service

      [Service]
      Type=oneshot
      RemainAfterExit=yes
      ExecStart=/usr/bin/docker network create -d=weavemesh ibe-development